twig:
    default_path: '%kernel.project_dir%/templates'
    file_name_pattern: '*.twig'
    globals:
        site_name: '%app.site_name%'
    paths:
        '%kernel.project_dir%/templates/bundles/TwigBundle': Twig
